---

ci:
  autoupdate_schedule: quarterly  # low frequency to reduce maintenance noise

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit.git
  rev: v0.12.4
  hooks:
  - id: ruff-format
    alias: ruff-format-first-pass
    name: ruff-format (first pass)

- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v3.2.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/astral-sh/ruff-pre-commit.git
  rev: v0.12.4
  hooks:
  - id: ruff-format
    alias: ruff-format-second-pass
    name: ruff-format (second pass)

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.5.5
  hooks:
  - id: remove-tabs

- repo: https://github.com/python-jsonschema/check-jsonschema.git
  rev: 0.33.2
  hooks:
  - id: check-github-workflows
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-jsonschema
    name: Check GitHub Workflows set timeout-minutes
    args:
    - --builtin-schema
    - github-workflows-require-timeout
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-readthedocs

- repo: https://github.com/pre-commit/pygrep-hooks.git
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-mock-methods
  - id: python-no-eval
  - id: python-no-log-warn
  - id: rst-backticks

- repo: https://github.com/codespell-project/codespell.git
  rev: v2.4.1
  hooks:
  - id: codespell
    exclude: >-
      ^\.github/\.json-schemas/.*\.json$

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.37.1
  hooks:
  - id: yamllint
    types:
    - file
    - yaml
    args:
    - --strict

...
